name: mutable_copy
description: MutableCopy simplify copy of immutable object. Unlike CopyWith, it allow to set null value.
version: 0.1.1
# author: Alex Vegner <alexvegner@gmail.com>
repository: https://github.com/AlexVegner/mutable_copy
issue_tracker: https://github.com/AlexVegner/mutable_copy/issues
homepage: https://github.com/AlexVegner/mutable_copy

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:


dev_dependencies:
  test: ^1.9.4
